IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ENTRADAHEALTH\SQLDevelopment')
CREATE LOGIN [ENTRADAHEALTH\SQLDevelopment] FROM WINDOWS
GO
CREATE USER [ENTRADAHEALTH\SQLDevelopment] FOR LOGIN [ENTRADAHEALTH\SQLDevelopment]
GO
GRANT VIEW DEFINITION TO [ENTRADAHEALTH\SQLDevelopment]
