IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ENTRADAHEALTH\SQLRW')
CREATE LOGIN [ENTRADAHEALTH\SQLRW] FROM WINDOWS
GO
CREATE USER [ENTRADAHEALTH\SQLRW] FOR LOGIN [ENTRADAHEALTH\SQLRW]
GO
