IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ENTRADAHEALTH\SQLRead')
CREATE LOGIN [ENTRADAHEALTH\SQLRead] FROM WINDOWS
GO
CREATE USER [ENTRADAHEALTH\SQLRead] FOR LOGIN [ENTRADAHEALTH\SQLRead]
GO
