IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ENTRADAHEALTH\SQLImplementation')
CREATE LOGIN [ENTRADAHEALTH\SQLImplementation] FROM WINDOWS
GO
CREATE USER [ENTRADAHEALTH\SQLImplementation] FOR LOGIN [ENTRADAHEALTH\SQLImplementation]
GO
GRANT EXECUTE TO [ENTRADAHEALTH\SQLImplementation]
GRANT SELECT TO [ENTRADAHEALTH\SQLImplementation]
GRANT VIEW DEFINITION TO [ENTRADAHEALTH\SQLImplementation]
