IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ENTRADAHEALTH\SQLSupport')
CREATE LOGIN [ENTRADAHEALTH\SQLSupport] FROM WINDOWS
GO
CREATE USER [ENTRADAHEALTH\SQLSupport] FOR LOGIN [ENTRADAHEALTH\SQLSupport]
GO
