IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ENTRADAHEALTH\qa_apps')
CREATE LOGIN [ENTRADAHEALTH\qa_apps] FROM WINDOWS
GO
CREATE USER [ENTRADAHEALTH\qa_apps] FOR LOGIN [ENTRADAHEALTH\qa_apps]
GO
