IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ENTRADAHEALTH\sqldevelopment')
CREATE LOGIN [ENTRADAHEALTH\sqldevelopment] FROM WINDOWS
GO
CREATE USER [ENTRADAHEALTH\SQLDevelopment] FOR LOGIN [ENTRADAHEALTH\sqldevelopment]
GO
GRANT VIEW DEFINITION TO [ENTRADAHEALTH\SQLDevelopment]
