IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ENTRADAHEALTH\reportDS')
CREATE LOGIN [ENTRADAHEALTH\reportDS] FROM WINDOWS
GO
CREATE USER [ENTRADAHEALTH\ReportDS] FOR LOGIN [ENTRADAHEALTH\reportDS]
GO
