IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ENTRADAHEALTH\PROD_App_Rec')
CREATE LOGIN [ENTRADAHEALTH\PROD_App_Rec] FROM WINDOWS
GO
CREATE USER [entradahealth\PROD_App_Rec] FOR LOGIN [ENTRADAHEALTH\PROD_App_Rec]
GO
GRANT EXECUTE TO [entradahealth\PROD_App_Rec]
