IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ENTRADAHEALTH\QA_apps')
CREATE LOGIN [ENTRADAHEALTH\QA_apps] FROM WINDOWS
GO
CREATE USER [ENTRADAHEALTH\qa_apps] FOR LOGIN [ENTRADAHEALTH\QA_apps]
GO
