CREATE TABLE [dbo].[Lookup_WTO_Provider]
(
[Key] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Value] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Lookup_WTO_Provider] ADD CONSTRAINT [PK__Lookup_W__C41E0288336B6C9B] PRIMARY KEY CLUSTERED  ([Key]) ON [PRIMARY]
GO
