CREATE TABLE [dbo].[Jobs_Custom]
(
[JobNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Custom1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom4] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom5] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom6] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom7] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom8] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom9] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom10] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom11] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom12] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom13] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom14] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom15] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom16] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom17] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom18] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom19] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom20] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom21] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom22] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom23] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom24] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom25] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom26] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom27] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom28] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom29] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom30] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom31] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom32] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom33] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom34] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom35] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom36] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom37] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom38] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom39] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom40] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom41] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom42] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom43] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom44] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom45] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom46] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom47] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom48] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom49] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom50] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Jobs_Custom] ADD CONSTRAINT [PK_Jobs_Custom] PRIMARY KEY CLUSTERED  ([JobNumber]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Jobs_Custom] ADD CONSTRAINT [FK_Jobs_Custom_Jobs] FOREIGN KEY ([JobNumber]) REFERENCES [dbo].[Jobs] ([JobNumber])
GO
