IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ENTRADAHEALTH\SQLImplementation')
CREATE LOGIN [ENTRADAHEALTH\SQLImplementation] FROM WINDOWS
GO
CREATE USER [ENTRADAHEALTH\SQLImplementation] FOR LOGIN [ENTRADAHEALTH\SQLImplementation]
GO
