CREATE TABLE [dbo].[SREEngineType](
	[SRETypeId] [int] NOT NULL,
	[SREType] [varchar](30) NULL,
 CONSTRAINT [pk_SRETypeId] PRIMARY KEY CLUSTERED 
(
	[SRETypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
